version: '3.8'

services:

  # Backend API
  smart-brain-api:
    container_name: backend
    #image: node:14.17
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment: 
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
      REDIS_URI: redis://redis:6379
    ports: 
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api
  
  # Postgres
  postgres:
    container_name: database
    #image: postgres
    build: ./postgres
    environment: 
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    restart: always
    ports:
      - "5433:5432"

  # Redis
  redis:
    container_name: jwt_session
    # image: redis:6.2.4
    build: ./redis
    ports:
      - "6379:6379"